method: "cosine"
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 8
max_length: 1024
layers_to_skip: 8
dataset_size: 8000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: True
diag: False # whether to force the LT to be a diagonal matrix
two_vectors: False # whether to force the LT to be a multiplication of two vectors
thri: False # whether to force the LT to be a lower triangular matrix
solver: "adam" # adam, cg, l-bfgs, trust-ncg are supported
loss: "cosine" # cosine, mse, elasticnet are supported
distances_path: null
num_A: 1
layers_to_skip: 8
merge_consecutive: False 
accurate: False # False will run cosine(xA, y - z) where z is the residual attention info, True to run cosine(xA + z, y)