model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 8
max_length: 1024
dataset_size: 8000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
distances_path: null
num_A: 1
layers_to_skip: 8
merge_consecutive: True 
