method: "lstsq"
model_path: "HuggingFaceTB/SmolLM-135M-Instruct"
dataset: "Open-Orca/SlimOrca"
dataset_column: "text"
batch_size: 24
max_length: 1024
dataset_size: 8000
dataset_subset: "train"
use_4bit: True
save_path: null
min_distance_layer: 20
save_transform_only: True
diag: False # whether to force the LT to be a diagonal matrix
alpha: 0 # regularization factor (use Ridge regularization)
distances_path: null
num_A: 1
layers_to_skip: 15
merge_consecutive: True
